name: Update README with dōteki
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '51 * * * *'  # Every hour at XX:51.

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necessary to push changes.
    steps:
      - name: Run dōteki action
        uses: welpo/doteki-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

[sections.blog]
plugin = "feed"
url = "https://medium.com/feed/@j0hnc0nn0r"  # Replace with your feed.

[sections.last_updated]
plugin = "current_date"
inline = true
